package com.yaelev.bank.customer;

import java.time.LocalDate;
import java.util.Objects;

public class Customer {

    private long id; // generated by database
    private long customerNo;
    private String fName;
    private String lName;
    private LocalDate dateOfBirth;
    private String ssn;
    private String address;
    private String email;

    // Default constructor
    public Customer() {
    }

    // Parameterized constructor, excluding id, since id is generated by the database
    public Customer(long customerNo, String fName, String lName, LocalDate dateOfBirth, String ssn, String address, String email) {
        this.customerNo = customerNo;
        this.fName = fName;
        this.lName = lName;
        this.dateOfBirth = dateOfBirth;
        this.ssn = ssn;
        this.address = address;
        this.email = email;
    }


    // Getters and setters
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getCustomerNo() {
        return customerNo;
    }

    public void setCustomerNo(long customerNo) {
        this.customerNo = customerNo;
    }

    public String getfName() {
        return fName;
    }

    public void setfName(String fName) {
        this.fName = fName;
    }

    public String getlName() {
        return lName;
    }

    public void setlName(String lName) {
        this.lName = lName;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getSsn() {
        return ssn;
    }

    public void setSsn(String ssn) {
        this.ssn = ssn;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Customer customer = (Customer) o;
        return id == customer.id && customerNo == customer.customerNo && Objects.equals(fName, customer.fName) && Objects.equals(lName, customer.lName) && Objects.equals(dateOfBirth, customer.dateOfBirth) && Objects.equals(ssn, customer.ssn) && Objects.equals(address, customer.address) && Objects.equals(email, customer.email);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, customerNo, fName, lName, dateOfBirth, ssn, address, email);
    }

    @Override
    public String toString() {
        return "Customer{" +
                "id=" + id +
                ", customerNo=" + customerNo +
                ", fName='" + fName + '\'' +
                ", lName='" + lName + '\'' +
                ", dateOfBirth=" + dateOfBirth +
                ", ssn='" + ssn + '\'' +
                ", address='" + address + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}
